import { Metadata } from "next";
import Footer from "./footer";
import Header from "./header";
// import "./error-wrapper";
// import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codevolution",
    absolute: "",
  },
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {Header()}
        {/* <ErrorWrapper> //</ErrorWrapper> */}{children}
        {Footer()}
      </body>
    </html>
  );
}
